apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: moment
  labels:
    app: airflow
data:
  AIRFLOW__CORE__EXECUTOR:           "LocalExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES:      "False"
  AIRFLOW__CORE__DAGS_FOLDER:        "/opt/airflow/dags/current/data_pipeline/airflow/dags"
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logs"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
  AIRFLOW__WEBSERVER__RBAC:          "True"
  AIRFLOW__API__AUTH_BACKENDS:       "airflow.api.auth.backend.basic_auth"
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
  AIRFLOW_HOME:                      "/opt/airflow"

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: moment
  labels:
    app: airflow
spec:
  type: ClusterIP
  selector:
    app: airflow
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
